stages:
  - build
  - dist
  - deploy

variables:
  DOCKER_IMAGE: eu.gcr.io/kubernetes-155014/larsvanherk/portfolio

Build App:
  stage: build
  image: node:6
  script:
    - yarn
    - yarn build
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - dist/*
      - dist/**/*
      - package.json
      - index.js

Build Docker Image:
  stage: dist
  image: google/cloud-sdk:alpine
  services:
    - docker:dind
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud docker -- build -t ${DOCKER_IMAGE}:${CI_COMMIT_SHA:0:8} .
    - gcloud docker -- tag ${DOCKER_IMAGE}:${CI_COMMIT_SHA:0:8} ${DOCKER_IMAGE}:latest
    - gcloud docker -- push ${DOCKER_IMAGE}:${CI_COMMIT_SHA:0:8}
    - gcloud docker -- push ${DOCKER_IMAGE}:latest
  only:
    - master

Deploy to Staging:
  stage: deploy
  image: google/cloud-sdk:alpine
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > key.json
    - gcloud components install kubectl
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials irrealis-prd --zone europe-west1-c --project kubernetes-155014
    - kubectl -n larsvanherk set image deployment/portfolio-staging app=${DOCKER_IMAGE}:${CI_COMMIT_SHA:0:8}
  environment:
    name: Staging
    url: https://staging.larsvanherk.com
  only:
    - master

Deploy to Production:
  stage: deploy
  image: google/cloud-sdk:alpine
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d > key.json
    - gcloud components install kubectl
    - gcloud auth activate-service-account --key-file key.json
    - gcloud container clusters get-credentials irrealis-prd --zone europe-west1-c --project kubernetes-155014
    - kubectl -n larsvanherk set image deployment/portfolio app=${DOCKER_IMAGE}:${CI_COMMIT_SHA:0:8}
  environment:
    name: Production
    url: https://www.larsvanherk.com
  when: manual
  only:
    - master
