stages:
  - build
  - dist
  - deploy

Build App:
  stage: build
  image: node:6.10
  script:
    - npm install
    - npm run-script build
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - dist/*
      - dist/**/*
      - package.json
      - index.js

Build Docker Image:
  stage: dist
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  script:
    - docker info
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.gitlab.com
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - Build App
  only:
    - tags
