stages:
  - build
  - dist
  - deploy

Build App:
  stage: build
  image: node:6.10
  script:
    - npm install
    - npm run-script build
    - npm run-script ci
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - dist/*
      - dist/**/*
      - k8s/dist/*
      - package.json
      - index.js

Build Docker Image:
  stage: dist
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
  script:
    - docker info
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.gitlab.com
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - Build App
  only:
    - tags

Deploy to Production:
  environment: Production
  stage: deploy
  image: google/cloud-sdk
  script:
    - echo "$GOOGLE_KEY" > key.json
    - gcloud auth activate-service-account --key-file key.json
    - gcloud config set compute/zone europe-west1-c
    - gcloud config set project kubernetes-155014
    - gcloud config set container/use_client_certificate True
    - gcloud container clusters get-credentials kube-prd
    - kubectl apply -f k8s/dist/deployment.yaml
  only:
    - tags