stages:
  - build
  - dist
  - deploy

Build App:
  stage: build
  image: node:6.10
  script:
    - npm install
    - npm run-script build
  artifacts:
    when: always
    expire_in: 5 days
    paths:
      - dist/*
      - dist/**/*
      - package.json
      - index.js

Build Docker Image:
  stage: dist
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker info
    - docker build -t registry.gitlab.com/work-portfolio/portfolio:$CI_BUILD_TAG .
    - docker push registry.gitlab.com/work-portfolio/portfolio:$CI_BUILD_TAG
  dependencies:
    - Build App
  only:
    - tags