/*
JS FOR PORTFOLIO LARS VAN HERK
COPYRIGHT LICENSE CREATIVE COMMONS BY-NC-SA
SEE http://creativecommons.org/licenses/by-nc-sa/3.0/ FOR MORE INFO
REFERENCED SCRIPTS BELONG TO THEIR RESPECTIVE OWNERS
    SEE FURTHER COMMENTS FOR EXTERNAL SOURCES
*/

